MVC_Core_lesson/Models/Phone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_Core_lesson.Secvices;

namespace MVC_Core_lesson.Models
{
  public class Phone : Entity
  {

    [Required(ErrorMessage = "Укажите модель")]
    [Display(Name = "Модель")]
    [Remote(action: "ValidateName",controller: "Validation",ErrorMessage = "Пользователь уже есть ")]
    public string Name { get; set; }

    [Required]
    [Display(Name = "Производитель")] 
    public int CompanyId { get; set; }
    

    [Display(Name = "Производитель")] public Company Company { get; set; }
    [Display(Name = "Цена")] public double Price { get; set; }
    [Display(Name = "Категория")] public int CategoryId { get; set; }
    [Display(Name = "Категория")] public Category Category { get; set; }
    [Display(Name = "Валюта")] public int MoneyId { get; set; }
    [Display(Name = "Валюта")] public Money Money { get; set; }
    [Display(Name = "На складе")] public bool InStock { get; set; }

    [Display(Name = "год выпуска")] public DateTime Date { get; set; }


    public IEnumerable<PhoneOnStock> Stocks { get; set; }
    public IEnumerable<Order> Orders { get; set; }
    public IEnumerable<Money> Monies { get; set; }
    public IEnumerable<Company> Companies { get; set; }
    public IEnumerable<Description> Descriptions { get; set; }
  }
}

MVC_Core_lesson/Controllers/DescriptionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Core_lesson.Database;
using MVC_Core_lesson.Models;

namespace MVC_Core_lesson.Controllers
{
  public class DescriptionsController : Controller
  {
    private readonly ApplicationContext _context;

    public DescriptionsController(ApplicationContext context)
    {
      _context = context;
    }

    // GET: Descriptions
    public async Task<IActionResult> Index()
    {
      var applicationContext = _context.Descriptions.Include(d => d.Phone);
      return View(await applicationContext.ToListAsync());
    }

    // GET: Descriptions/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var description = await _context.Descriptions
        .Include(d => d.Phone)
        .FirstOrDefaultAsync(m => m.Id == id);
      if (description == null)
      {
        return NotFound();
      }

      return View(description);
    }

    // GET: Descriptions/Create
    public IActionResult Create()
    {
      ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "Name");
      ViewData["Rating"] = new SelectList(new int[] {1, 2, 3, 4, 5});
      return View();
    }

    // POST: Descriptions/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Text,Rating,PhoneId")] Description description)
    {
      if (ModelState.IsValid)
      {
        _context.Add(description);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }

      ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "Name", description.PhoneId);
      return View(description);
    }

    // GET: Descriptions/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var description = await _context.Descriptions.FindAsync(id);
      if (description == null)
      {
        return NotFound();
      }

      ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "Name", description.PhoneId);
      return View(description);
    }

    // POST: Descriptions/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Text,Rating,PhoneId")] Description description)
    {
      if (id != description.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(description);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!DescriptionExists(description.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }

        return RedirectToAction(nameof(Index));
      }

      ViewData["PhoneId"] = new SelectList(_context.Phones, "Id", "Name", description.PhoneId);
      return View(description);
    }

    // GET: Descriptions/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var description = await _context.Descriptions
        .Include(d => d.Phone)
        .FirstOrDefaultAsync(m => m.Id == id);
      if (description == null)
      {
        return NotFound();
      }

      return View(description);
    }

    // POST: Descriptions/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var description = await _context.Descriptions.FindAsync(id);
      _context.Descriptions.Remove(description);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool DescriptionExists(int id)
    {
      return _context.Descriptions.Any(e => e.Id == id);
    }
  }
}

MVC_Core_lesson/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Core_lesson.Database;
using MVC_Core_lesson.Enums;
using MVC_Core_lesson.Models;
using MVC_Core_lesson.ViewModels;

namespace MVC_Core_lesson.Controllers
{
  public class PhonesController : Controller
  {
    private readonly ApplicationContext _context;
    public int pageSize = 3;

    private IHostingEnvironment _environment;

    public PhonesController(ApplicationContext context, IHostingEnvironment environment)
    {
      _context = context;
      _environment = environment;
    }

    // GET: Phones
    public async Task<IActionResult> Index(
      string name,
      string CategoryName,
      double? priceFrom,
      double? priceTo,
      int? companyId,
      int? categoryId,
      int? moneyId,
      bool? inStock,
      SortPhones sortPhones = SortPhones.NameAsc,
      int page = 1
    )
    {
      IQueryable<Phone> phones = _context.Phones
        .Include(p => p.Category)
        .Include(p => p.Company)
        .Include(m => m.Money);
        
      if (!string.IsNullOrWhiteSpace(name))
      {
        phones = phones.Where(s => s.Name.Contains(name));
      }

      if (!string.IsNullOrWhiteSpace(CategoryName))
      {
        phones = phones.Where(s => s.Category.Name.Contains(CategoryName));
      }
      
      if (priceFrom.HasValue)
      {
        phones = phones.Where(s => s.Price >= priceFrom.Value);
      }

      if (priceTo.HasValue)
      {
        phones = phones.Where(s => s.Price <= priceTo.Value);
      }


      if (companyId.HasValue)
      {
        phones = phones.Where(s => s.CompanyId == companyId.Value);
      }

      if (categoryId.HasValue)
      {
        phones = phones.Where(s => s.CategoryId == categoryId.Value);
      }

      if (moneyId.HasValue)
      {
        phones = phones.Where(s => s.MoneyId == moneyId.Value);
      }

      ViewBag.NameSort = sortPhones == SortPhones.NameAsc ? SortPhones.NameDesc : SortPhones.NameAsc;
      ViewBag.InStockSort = sortPhones == SortPhones.InStockAsc ? SortPhones.InStockDesc : SortPhones.InStockAsc;
      ViewBag.PriceSort = sortPhones == SortPhones.PriceAsc ? SortPhones.PriceDesc : SortPhones.PriceAsc;
      ViewBag.CompanySort = sortPhones == SortPhones.CompanyAsc ? SortPhones.CompanyDesc : SortPhones.CompanyAsc;
      ViewBag.MoneySort = sortPhones == SortPhones.MoneyAsc ? SortPhones.MoneyDesc : SortPhones.MoneyAsc;
      ViewBag.CategorySort = sortPhones == SortPhones.CategoryAsc ? SortPhones.CategoryDesc : SortPhones.CategoryAsc;


      switch (sortPhones)
      {
        case SortPhones.NameAsc:
          phones = phones.OrderBy(s => s.Name);
          break;
        case SortPhones.NameDesc:
          phones = phones.OrderByDescending(s => s.Name);
          break;
        case SortPhones.CategoryNameAsc:
          phones = phones.OrderBy(s => s.Category.Name);
          break;
        case SortPhones.CategoryNameDesc:
          phones = phones.OrderByDescending(s => s.Category.Name);
          break;
        case SortPhones.PriceAsc:
          phones = phones.OrderBy(s => s.Price);
          break;
        case SortPhones.PriceDesc:
          phones = phones.OrderByDescending(s => s.Price);
          break;
        case SortPhones.CompanyAsc:
          phones = phones.OrderBy(s => s.Company.Name);
          break;
        case SortPhones.CompanyDesc:
          phones = phones.OrderByDescending(s => s.Company.Name);
          break;
        case SortPhones.MoneyAsc:
          phones = phones.OrderBy(s => s.Money.CurrencyCode);
          break;
        case SortPhones.MoneyDesc:
          phones = phones.OrderByDescending(s => s.Money.CurrencyCode);
          break;
        case SortPhones.CategoryAsc:
          phones = phones.OrderBy(s => s.Category.Name);
          break;
        case SortPhones.CategoryDesc:
          phones = phones.OrderByDescending(s => s.Category.Name);
          break;
        case SortPhones.InStockAsc:
          phones = phones.OrderBy(s => s.InStock == true);
          break;
        case SortPhones.InStockDesc:
          phones = phones.OrderByDescending(s => s.InStock != true);
          break;
      }

      PageViewModel viewModel = new PageViewModel(phones.Count(), page, pageSize);
      
      IndexPhoneViewModel model = new IndexPhoneViewModel()
      {
        Phones = phones.Skip((page - 1)
                             * (pageSize)).Take(pageSize).ToList(),
        Name = name,
        CompanyId = companyId,
        MoneyId = moneyId,
        CategoryId = categoryId,
        PriceFrom = priceFrom,
        PriceTo = priceTo,
        Companies = new SelectList(_context.Companies, "Id", "Name"),
        Moneis = new SelectList(_context.Monies, "Id", "CurrencyCode"),
        Categories = new SelectList(_context.Categories, "Id", "Name"),
        ViewModel = viewModel
      };

      return View(model);
    }

    // GET: Phones/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      ViewData["MoneyId"] = new SelectList(_context.Monies, "Id", "CurrencyCode");
      var phone = await _context.Phones
        .Include(p => p.Category)
        .Include(p => p.Company)
        .Include(m => m.Money)
        .Include(p => p.Descriptions)
        .FirstOrDefaultAsync(m => m.Id == id);


      ViewBag.PhoneList = _context.Descriptions
        .Include(d => d.Phone).Where(m => m.Id == id).ToList();


      if (phone == null)
      {
        return NotFound();
      }

      return View(phone);
    }

    // GET: Phones/Create
    public IActionResult Create()
    {
      ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name");
      ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
      ViewData["MoneyId"] = new SelectList(_context.Monies, "Id", "CurrencyCode");
      return View();
    }

    // POST: Phones/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,CompanyId,Price,CategoryId,MoneyId,InStock")]
      Phone phone)
    {
      if (ModelState.IsValid)
      {
        _context.Add(phone);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }

      ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", phone.CategoryId);
      ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", phone.CompanyId);
      ViewData["MoneyId"] = new SelectList(_context.Monies, "Id", "CurrencyCode", phone.MoneyId);
      return View(phone);
    }

    // GET: Phones/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var phone = await _context.Phones.FindAsync(id);
      if (phone == null)
      {
        return NotFound();
      }

      ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", phone.CategoryId);
      ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", phone.CompanyId);
      ViewData["MoneyId"] = new SelectList(_context.Monies, "Id", "CurrencyCode", phone.MoneyId);
      return View(phone);
    }

    // POST: Phones/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CompanyId,Price,CategoryId,MoneyId,InStock")]
      Phone phone)
    {
      if (id != phone.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(phone);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!PhoneExists(phone.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }

        return RedirectToAction(nameof(Index));
      }

      ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", phone.CategoryId);
      ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", phone.CompanyId);
      ViewData["MoneyId"] = new SelectList(_context.Monies, "Id", "CurrencyCode", phone.MoneyId);
      return View(phone);
    }

    // GET: Phones/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null)
      {
        return NotFound();
      }

      var phone = await _context.Phones
        .Include(p => p.Category).Include(m => m.Money)
        .FirstOrDefaultAsync(m => m.Id == id);
      if (phone == null)
      {
        return NotFound();
      }

      return View(phone);
    }

    // POST: Phones/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      var phone = await _context.Phones.FindAsync(id);
      _context.Phones.Remove(phone);
      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool PhoneExists(int id)
    {
      return _context.Phones.Any(e => e.Id == id);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> EditCurrency(int id, [Bind("Id,Name,Company,Price,CategoryId,MoneyId")]
      Phone phone)
    {
      if (!ModelState.IsValid)
      {
        return NotFound();
      }


      double newPrice = 0;
      switch (phone.MoneyId)
      {
        case 1: //"RUB"
          if (phone.Price > 1000)
          {
            newPrice = phone.Price / 63;
          }
          else
          {

MVC_Core_lesson/Views/Phones/Create.cshtml
@model MVC_Core_lesson.Models.Phone

@{
    ViewData["Title"] = "Новый телефон";
}

<h2>Новый телефон</h2>

<h4>Заполни все поля</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="MoneyId" class="control-label"></label>
                <select asp-for="MoneyId" class="form-control" asp-items="ViewBag.MoneyId"></select>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="InStock" /> @Html.DisplayNameFor(model => model.InStock)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_Core_lesson/Views/Phones/Delete.cshtml
@model MVC_Core_lesson.Models.Phone

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Phone</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_Core_lesson/Views/Phones/Details.cshtml
@model Phone

@{
    ViewData["Title"] = @Model.Name;
}

<h2>@Model.Name</h2>
<div style="width: 200px;">
    <form asp-action="EditCurrency">
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="Id"/>
        <input type="hidden" asp-for="Name"/>
        <input type="hidden" asp-for="Company"/>
        <input type="hidden" asp-for="Price"/>
        <input type="hidden" asp-for="CategoryId"/>

        <div class="form-group">
            <label asp-for="MoneyId" class="control-label"></label>

            <select asp-for="MoneyId" class="form-control" asp-items="ViewBag.MoneyId">

                <option selected="selected" disabled="disabled" aria-disabled="True">Выберети валюту</option>

            </select>
            <span asp-validation-for="MoneyId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Изменить валюту" class="btn btn-success"/>
        </div>
    </form>
</div>
<div>
    <h4>@Model.Category.Name</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price) @Model.Money.CurrencyCode
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
</div>

<div>
    @if (ViewBag.PhoneList != null)
    {
        <table class="table table-striped">

            <thead>
            <tr>
                <th>
                    Имя
                </th>
                <th>
                    Описание
                </th> 
                <th>
                    Оценка
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var description in ViewBag.PhoneList)
            {
                <tr>

                    <td>@description.Name</td>
                    <td>@description.Text</td>
                    <td>@description.Rating</td>
                    <td><a asp-action="Create" asp-controller="Descriptions">добавить</a></td>
                </tr>
                <tr>


                </tr>
            }

        </table>
    }

</div>


<div>
    <a asp-action="OnCompanySite" asp-route-Company="@Model.Company.Name" class="btn btn-info">Сайт @Model.Company.Name</a>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-default">Редактировать</a>
    <a asp-action="Index" class="btn btn-primary">Вернуться к списку</a>
</div>

MVC_Core_lesson/Views/Phones/Edit.cshtml
@model MVC_Core_lesson.Models.Phone

@{
    ViewData["Title"] = Model.Name;
}

<h2>Редактирование</h2>

<h4>@Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label"></label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId"></select>
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoneyId" class="control-label"></label>
                <select asp-for="MoneyId" class="form-control" asp-items="ViewBag.MoneyId"></select>
                <span asp-validation-for="MoneyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Соханить" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}